import { ThemeContextProvider } from "@/context/store";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Toaster } from "react-hot-toast";
import CartSection from "@/components/Sections/CartSection";
import Header from "@/components/UI/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />

        <ThemeContextProvider>
          <CartSection />
          <main className="lg:mx-36 xl:mx-44 md:mx-20 sm:mx-10 mx-4">
            <Header />
            {children}
          </main>
        </ThemeContextProvider>
      </body>
    </html>
  );
}
